# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 5000

format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$python\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$docker_context\
$gcloud\
$kubernetes\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[python]
symbol = "󰌠 "
pyenv_version_name = true

[gcloud]
symbol = " "
format = "[$symbol$project]($style) "

[kubernetes]
symbol = "ﴱ "
format = '[$symbol$context( \($namespace\)) ]($style)'
disabled = true
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "k8s"
"kind-kind" = "kind-default"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[rust]
symbol = "  "
