OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
DYNAMIC_TAPPING_TERM_ENABLE = yes
CAPS_WORD_ENABLE = yes
LTO_ENABLE      = yes
MOUSEKEY_ENABLE = no    # Mouse keys
EXTRAKEY_ENABLE = yes # Audio control and System control
KEY_OVERRIDE_ENABLE = yes
