return {
	settings = {
		python = {
			pythonPath = "python",
			venvPath = "",
			analysis = {
				logLevel = "Warning",
				autoImportCompletions = true,
				autoSearchPaths = true,
				diagnosticMode = "openFilesOnly",
				stubPath = "typings",
				typeshedPaths = {},
				diagnosticSeverityOverrides = {},
				typeCheckingMode = "basic",
				useLibraryCodeForTypes = true,
			},
			formatting = {
				provider = "autopep8",
				blackPath = "black",
				blackArgs = {},
				blackdPath = "blackd",
				blackdHTTPURL = "",
				blackdHTTPHeaders = {},
				yapfPath = "yapf",
				yapfArgs = {},
				autopep8Path = "autopep8",
				autopep8Args = {},
			},
			linting = {
				enabled = true,
				flake8Enabled = false,
				banditEnabled = false,
				mypyEnabled = false,
				pytypeEnabled = false,
				pycodestyleEnabled = false,
				prospectorEnabled = false,
				pydocstyleEnabled = false,
				pylamaEnabled = false,
				pylintEnabled = false,
			},
			sortImports = {
				path = "",
				args = {},
			},
			pyright = {
				server = "",
				disableCompletion = false,
				disableDiagnostics = false,
				disableProgressNotifications = false,
				completion = {
					importSupport = true,
					snippetSupport = true,
				},
				organizeimports = {
					provider = "pyright",
				},
			},
		},
	},
}
